Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2023-10, with the labels that each got.

#381 Build Haddocks on 9.2
  .github/workflows/ci.yml
Labels: continuous integration

#401 README.md: link to report pdf
  README.md
Labels: documentation

#371 Run the ChainSync client with limits
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/test/infra-test/Ouroboros/Network/Driver/Limits/Extras.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/GenesisTest.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/Sync.hs
Labels: Genesis

#406 Add the block fetch mock server to the peer simulator
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/GenesisTest.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/PointSchedule.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/Sync.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/PeerSimulator/BlockFetch.hs
Labels: Genesis

#408 Update to GHC 9.6.3
  .github/workflows/cabal.project.local
  .github/workflows/ci.yml
  flake.lock
  nix/haskell.nix
  nix/shell.nix
  nix/tools.nix
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Ouroboros/Consensus/ChainGenerator/Some.hs
Labels: continuous integration

#411 Cleanup various things
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/test/infra-test/Main.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/BlockTree.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/ChainDb.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/GenesisTest.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/PointScheduleTest.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/Sync.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/Genesis/Setup.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/Genesis/Tests.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/Genesis/Tests/LongRangeAttack.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/PeerSimulator/Config.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/PeerSimulator/Handlers.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/PeerSimulator/Resources.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/PeerSimulator/Run.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/PointSchedule.hs
Labels: Genesis

#421 Remove the ConnectionThread data type
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/PeerSimulator/Run.hs
Labels: Genesis

#430 Enable the generation of multiple adversarial chains for the peer simulator
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Ouroboros/Consensus/ChainGenerator/Adversarial.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Ouroboros/Consensus/ChainGenerator/Honest.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Ouroboros/Consensus/ChainGenerator/Params.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/QuickCheck/Extras.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/Adversarial.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/Honest.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/Genesis/Setup.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/Genesis/Setup/Classifiers.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/Genesis/Setup/GenChains.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/Genesis/Tests/LongRangeAttack.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/PeerSimulator/Config.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/PeerSimulator/Run.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/PointSchedule.hs
Labels: Genesis

#431 Move Genesis tests to `ouroboros-consensus-diffusion:consensus-test`
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-diffusion/test/consensus-test/Main.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/BlockTree.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup/Classifiers.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup/GenChains.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/LongRangeAttack.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Network/AnchoredFragment/Extras.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Network/Driver/Limits/Extras.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/BlockFetch.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Config.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Handlers.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Resources.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/ScheduledChainSyncServer.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Trace.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule.hs
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/test/infra-test/Main.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/Genesis/Tests.hs
Labels: Genesis

#360 Publish `utxo-db.pdf` and `utxo-db-api.pdf` docs on the website
  .github/workflows/documentation.yml
  docs/tech-reports/report/.gitignore
  docs/tech-reports/report/chapters/appendix/byron.tex
  docs/tech-reports/report/chapters/appendix/shelley.tex
  docs/tech-reports/report/chapters/conclusions/conclusions.tex
  docs/tech-reports/report/chapters/conclusions/technical.tex
  docs/tech-reports/report/chapters/consensus/ledger.tex
  docs/tech-reports/report/chapters/consensus/protocol.tex
  docs/tech-reports/report/chapters/consensus/serialisation.tex
  docs/tech-reports/report/chapters/future/ebbs.tex
  docs/tech-reports/report/chapters/future/genesis.tex
  docs/tech-reports/report/chapters/future/lowdensity.tex
  docs/tech-reports/report/chapters/future/misc.tex
  docs/tech-reports/report/chapters/hfc/misc.tex
  docs/tech-reports/report/chapters/hfc/overview.tex
  docs/tech-reports/report/chapters/hfc/time.tex
  docs/tech-reports/report/chapters/intro/intro.tex
  docs/tech-reports/report/chapters/intro/nonfunctional.tex
  docs/tech-reports/report/chapters/intro/overview.tex
  docs/tech-reports/report/chapters/miniprotocols/chainsyncclient.tex
  docs/tech-reports/report/chapters/miniprotocols/servers.tex
  docs/tech-reports/report/chapters/storage/chaindb.tex
  docs/tech-reports/report/chapters/storage/chainselection.tex
  docs/tech-reports/report/chapters/storage/immutabledb.tex
  docs/tech-reports/report/chapters/storage/ledgerdb.tex
  docs/tech-reports/report/chapters/storage/mempool.tex
  docs/tech-reports/report/chapters/storage/overview.tex
  docs/tech-reports/report/chapters/storage/volatiledb.tex
  docs/tech-reports/report/chapters/testing/consensus.tex
  docs/tech-reports/report/chapters/testing/storage.tex
  docs/tech-reports/report/cleanbuild.sh
  docs/tech-reports/report/presentations/genesis-2.0.tex
  docs/tech-reports/report/presentations/genesis.tex
  docs/tech-reports/report/references.bib
  docs/tech-reports/report/report.dict
  docs/tech-reports/report/report.tex
  docs/tech-reports/report/spellcheck.sh
  docs/tech-reports/report/unsoundswitch/LICENSE
  docs/tech-reports/report/unsoundswitch/NOTICE
  docs/tech-reports/report/unsoundswitch/UnsoundSwitch.hs
  docs/tech-reports/report/unsoundswitch/cabal.project
  docs/tech-reports/report/unsoundswitch/unsoundswitch.cabal
  docs/tech-reports/report/watch.sh
  docs/tech-reports/utxo-db/Makefile
  docs/tech-reports/utxo-db/img/hstore-anticaching-fig1.png
  docs/tech-reports/utxo-db/utxo-db-api.tex
  docs/tech-reports/utxo-db/utxo-db.bib
  docs/tech-reports/utxo-db/utxo-db.tex
  docs/website/contents/about-ouroboros/References.md
  docs/website/contents/for-developers/TechnicalReports.md
  docs/website/sidebars.js
  nix/pdfs.nix
Labels: UTxO-HD

#432 Send `AwaitReply` to prevent timeouts.
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Network/Driver/Limits/Extras.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Handlers.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/ScheduledChainSyncServer.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Trace.hs
Labels: Genesis

#437 add docs for PointSchedule
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule.hs
Labels: Genesis

#452 Add a test to check that timeouts are indeed enforced
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-diffusion/test/consensus-test/Main.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/BlockTree.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/LongRangeAttack.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/StateView.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Tests.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Tests/Timeouts.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Trace.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule.hs
Labels: Genesis

#456 Cleanup
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Tests/Timeouts.hs
Labels: Genesis

#454 Cleanup and documenation
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  docs/website/contents/for-developers/StyleGuide.md
  docs/website/contents/for-developers/VersioningSchemeDecision.md
  scripts/docs/haddocks.sh
  scripts/docs/modules-consensus.svg
  scripts/docs/packages-consensus.svg
  scripts/docs/prologue.haddock
  scripts/docs/prologue.md
Labels: documentation

#455 Remove unused NoThunks constraint, specialize mk in BlockForging
  ouroboros-consensus-cardano-legacy-block/src/Legacy/LegacyBlock.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Ledger.hs
  ouroboros-consensus-cardano/src/tools/Cardano/Tools/DBSynthesizer/Forging.hs
  ouroboros-consensus-diffusion/src/diffusion-testlib/Test/ThreadNet/Network.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Block/Forging.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Forging.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Ledger.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Mempool.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/SupportsMempool.hs
  ouroboros-consensus/src/tutorials/Ouroboros/Consensus/Tutorial/Simple.lhs
Labels: UTxO-HD

#464 Disable `dist-newstyle` caching in GHA
  .github/workflows/ci.yml
Labels: continuous integration

#459 Discard the test cases _before_ running the peer simulator if possible?
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/LongRangeAttack.hs
Labels: Genesis

#458 Add a test to check that rollbacks actually happen
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/BlockTree.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Tests.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Tests/Rollback.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule.hs
Labels: Genesis

#450 Convert FastAdversary to a frequency-based generator
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/BlockTree.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup/Classifiers.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup/GenChains.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/LongRangeAttack.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule.hs
Labels: Genesis

#460 A few `HTrans` instances
  ouroboros-consensus-cardano-legacy-block/ouroboros-consensus-cardano-legacy-block.cabal
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Convert.hs
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Data/SOP/Match.hs
  ouroboros-consensus/src/ouroboros-consensus/Data/SOP/OptNP.hs
Labels: UTxO-HD
