Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2023-11, with the labels that each got.

#463 Lift `HTrans`-like functions to `HardForkBlock`-related datatypes
  ouroboros-consensus-cardano-legacy-block/ouroboros-consensus-cardano-legacy-block.cabal
  ouroboros-consensus-cardano-legacy-block/src/Ouroboros/Consensus/HardFork/Trans.hs
Labels: UTxO-HD

#472 Missing (general) instances for the `LegacyBlock`
  .github/workflows/ci.yml
  ouroboros-consensus-cardano-legacy-block/ouroboros-consensus-cardano-legacy-block.cabal
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Byron/Ledger.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Cardano/Block.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Cardano/CanHardFork.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Cardano/Ledger.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Convert.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/LegacyBlock.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Shelley/Ledger.hs
  ouroboros-consensus-cardano-legacy-block/src/Ouroboros/Consensus/Legacy/Block.hs
  ouroboros-consensus-cardano-legacy-block/src/Ouroboros/Consensus/Legacy/Util.hs
Labels: UTxO-HD

#499 Use `bracketChainSync` in the peer simulator
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Resources.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
Labels: Genesis

#507 Introduce `StateViewTracers` as a cleaner mechanism to gather information
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/StateView.hs
Labels: Genesis

#511 Update docusaurus
  docs/website/contents/for-developers/AbstractProtocol.md
  docs/website/contents/for-developers/HardWonWisdom.md
  docs/website/contents/for-developers/ReleaseProcess.md
  docs/website/docusaurus.config.js
  docs/website/package.json
  docs/website/yarn.lock
Labels: documentation

#473 Finalise Cardano Legacy Block
  ouroboros-consensus-cardano-legacy-block/ouroboros-consensus-cardano-legacy-block.cabal
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Byron.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Byron/Ledger.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Byron/Node.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Cardano.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Cardano/Block.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Cardano/CanHardFork.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Cardano/Ledger.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Cardano/Node.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Shelley.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Shelley/Ledger.hs
  ouroboros-consensus-cardano-legacy-block/src/Legacy/Shelley/Node.hs
  ouroboros-consensus-cardano-legacy-block/src/Ouroboros/Consensus/HardFork/Trans.hs
  ouroboros-consensus-cardano-legacy-block/src/Ouroboros/Consensus/Legacy/Block.hs
Labels: UTxO-HD

#523 enable NodeToNode V13 protocol
  ouroboros-consensus-cardano/changelog.d/20231127_134955_alexander.esgen_enable_n2n_13.md
  ouroboros-consensus-cardano/changelog.d/20231127_154208_alexander.esgen_enable_n2n_13.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Node.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/NetworkProtocolVersion.hs
  ouroboros-consensus-cardano/test/cardano-test/Main.hs
  ouroboros-consensus-cardano/test/cardano-test/Test/Consensus/Cardano/SupportedNetworkProtocolVersion.hs
  ouroboros-consensus-cardano/test/shelley-test/Main.hs
  ouroboros-consensus-cardano/test/shelley-test/Test/Consensus/Shelley/SupportedNetworkProtocolVersion.hs
  ouroboros-consensus/changelog.d/20231127_154213_alexander.esgen_enable_n2n_13.md
  ouroboros-consensus/changelog.d/20231127_160419_alexander.esgen_enable_n2n_13.md
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/SupportedNetworkProtocolVersion.hs
Labels: no changelog

#521 UTxO-HD: LedgerDB API rewrite and V1 implementation
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/API.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/API/DiskPolicy.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/BackingStore.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/DbChangelog.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Common.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Flush.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Forker.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Init.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Snapshots.hs
Labels: UTxO-HD

#528 Relax text bound
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: no changelog

#525 Do not even propagate future headers
  ouroboros-consensus-diffusion/changelog.d/20231129_105548_nick.frisby_ChainSync_future.md
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Network/NodeToNode.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
  ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Network.hs
  ouroboros-consensus/changelog.d/20231129_105543_nick.frisby_ChainSync_future.md
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Fragment/InFuture.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/InFutureCheck.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/Time.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/ChainSync/Client.hs
Labels: enhancement
