Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2023-09, with the labels that each got.

#326 Update `utxo-db-api.pdf`
  docs/utxo-hd/utxo-db/Makefile
  docs/utxo-hd/utxo-db/img/hstore-anticaching-fig1.png
  docs/utxo-hd/utxo-db/utxo-db-api.tex
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: documentation, UTxO-HD

#330 Deploy `utxo-db` and `utxo-db-api` docs
  docs/pdfs/report/.gitignore
  docs/pdfs/report/chapters/appendix/byron.tex
  docs/pdfs/report/chapters/appendix/shelley.tex
  docs/pdfs/report/chapters/conclusions/conclusions.tex
  docs/pdfs/report/chapters/conclusions/technical.tex
  docs/pdfs/report/chapters/consensus/ledger.tex
  docs/pdfs/report/chapters/consensus/protocol.tex
  docs/pdfs/report/chapters/consensus/serialisation.tex
  docs/pdfs/report/chapters/future/ebbs.tex
  docs/pdfs/report/chapters/future/genesis.tex
  docs/pdfs/report/chapters/future/lowdensity.tex
  docs/pdfs/report/chapters/future/misc.tex
  docs/pdfs/report/chapters/hfc/misc.tex
  docs/pdfs/report/chapters/hfc/overview.tex
  docs/pdfs/report/chapters/hfc/time.tex
  docs/pdfs/report/chapters/intro/intro.tex
  docs/pdfs/report/chapters/intro/nonfunctional.tex
  docs/pdfs/report/chapters/intro/overview.tex
  docs/pdfs/report/chapters/miniprotocols/chainsyncclient.tex
  docs/pdfs/report/chapters/miniprotocols/servers.tex
  docs/pdfs/report/chapters/storage/chaindb.tex
  docs/pdfs/report/chapters/storage/chainselection.tex
  docs/pdfs/report/chapters/storage/immutabledb.tex
  docs/pdfs/report/chapters/storage/ledgerdb.tex
  docs/pdfs/report/chapters/storage/mempool.tex
  docs/pdfs/report/chapters/storage/overview.tex
  docs/pdfs/report/chapters/storage/volatiledb.tex
  docs/pdfs/report/chapters/testing/consensus.tex
  docs/pdfs/report/chapters/testing/storage.tex
  docs/pdfs/report/cleanbuild.sh
  docs/pdfs/report/presentations/genesis-2.0.tex
  docs/pdfs/report/presentations/genesis.tex
  docs/pdfs/report/references.bib
  docs/pdfs/report/report.dict
  docs/pdfs/report/report.tex
  docs/pdfs/report/spellcheck.sh
  docs/pdfs/report/unsoundswitch/LICENSE
  docs/pdfs/report/unsoundswitch/NOTICE
  docs/pdfs/report/unsoundswitch/UnsoundSwitch.hs
  docs/pdfs/report/unsoundswitch/cabal.project
  docs/pdfs/report/unsoundswitch/unsoundswitch.cabal
  docs/pdfs/report/watch.sh
  docs/pdfs/utxo-db/Makefile
  docs/pdfs/utxo-db/img/hstore-anticaching-fig1.png
  docs/pdfs/utxo-db/utxo-db-api.tex
  docs/pdfs/utxo-db/utxo-db.bib
  docs/pdfs/utxo-db/utxo-db.tex
  docs/website/contents/about-ouroboros/utxo-hd.md
  nix/pdfs.nix
Labels: documentation, UTxO-HD, continuous integration

#332 Integrate checked `StrictMVars` from `strict-checked-vars`
  .github/workflows/ci.yml
  cabal.project
  flake.lock
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Run.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBTruncater/Run.hs
  ouroboros-consensus-protocol/src/ouroboros-consensus-protocol/Ouroboros/Consensus/Protocol/Ledger/HotKey.hs
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/changelog.d/20230901_110639_joris_114_integrate_strict_checked_mvars.md
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Background.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Index/Cache.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/EarlyExit.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/IOLike.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/NormalForm/StrictMVar.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/LogicalClock.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/Orphans/NoThunks.hs
  ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Node/Praos.hs
  ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Protocol/Praos.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/BlockchainTime/Simple.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/ResourceRegistry.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Util/MonadSTM/NormalForm.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/StateMachine.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ImmutableDB/StateMachine.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/VolatileDB/StateMachine.hs
Labels: enhancement

#333 Update various Nix things
  flake.lock
  flake.nix
  nix/shell.nix
  nix/tools.nix
Labels: continuous integration

#349 Avoid HF projections in mempool
  ouroboros-consensus-cardano-legacy-block/src/Legacy/LegacyBlock.hs
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/byronspec/Ouroboros/Consensus/ByronSpec/Ledger/Mempool.hs
  ouroboros-consensus-cardano/src/shelley-testlib/Test/ThreadNet/TxGen/Shelley.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Mempool.hs
  ouroboros-consensus-cardano/test/byron-test/Test/ThreadNet/DualByron.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator/A.hs
  ouroboros-consensus/bench/mempool-bench/Bench/Consensus/Mempool/TestBlock.hs
  ouroboros-consensus/src/mock-block/Ouroboros/Consensus/Mock/Ledger/Block.hs
  ouroboros-consensus/src/ouroboros-consensus/Data/SOP/Functors.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/InjectTxs.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Ledger/Query.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Mempool.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Dual.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Query.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/SupportsMempool.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Impl/Common.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Query.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Update.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/LocalStateQuery/Server.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool/StateMachine.hs
Labels: UTxO-HD

#356 Expose ChainDB statistics
  ouroboros-consensus-cardano/app/beacon.hs
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/DiffSeq.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/API.hs
Labels: UTxO-HD

#368 Enter block tree
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/test/infra-test/Ouroboros/Network/AnchoredFragment/Extras.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/BlockTree.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/GenChain.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/GenesisTest.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/Sync.hs
Labels: Genesis

#379 Build db-analyser and friends without asserts for more GHC versions
  flake.nix
  nix/ci.nix
  nix/haskell.nix
  ouroboros-consensus-cardano/README.md
Labels: continuous integration
