Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2024-05, with the labels that each got.

#1007 Make the LoP follow GSM states
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Network/NodeToNode.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node/GSM.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/ChainSync.hs
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/State.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Node/GsmState.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/LeakyBucket.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/ChainSync/Client.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/Util/LeakyBucket/Tests.hs
Labels: Genesis

#1098 Upgrade to latest docusaurus
  docs/website/package.json
  docs/website/yarn.lock
Labels: documentation

#1096 PreflightGuide: new section on the leader schedule
  docs/website/contents/for-developers/PreflightGuide.md
  docs/website/contents/for-developers/PreflightGuide/plot-active-slots.png
  docs/website/contents/for-developers/PreflightGuide/plot-grinding.png
  docs/website/contents/for-developers/PreflightGuide/plot-pooltool-slot-battles.png
  docs/website/contents/for-developers/PreflightGuide/plot-single-slot-leaders.png
  docs/website/contents/for-developers/PreflightGuide/plot.py
Labels: documentation

#1100 Re-add `ShowProxy SlotNo` orphan instance
  cabal.project
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/Orphans.hs
Labels: no changelog

#1101 Release Consensus packages for Node 8.11
  README.md
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/changelog.d/20240227_142647_alexander.esgen_pipelining_criterion.md
  ouroboros-consensus-cardano/changelog.d/20240227_143106_alexander.esgen_pipelining_criterion.md
  ouroboros-consensus-cardano/changelog.d/20240328_165135_alexander.esgen_milestone_11_gdd_governor_squashed.md
  ouroboros-consensus-cardano/changelog.d/20240409_142855_alexander.esgen_duncan_tiebreaker.md
  ouroboros-consensus-cardano/changelog.d/20240430_233346_Lucsanszky_integration_8_11.md
  ouroboros-consensus-cardano/changelog.d/20240503_143529_joosep.jaager_accountstate_query.md
  ouroboros-consensus-cardano/changelog.d/20240507_211718_alexey.kuleshevich_hardfork_initiation.md
  ouroboros-consensus-cardano/changelog.d/chaindb-args-javier.md
  ouroboros-consensus-cardano/changelog.d/proto-translate-javier.md
  ouroboros-consensus-cardano/changelog.d/utxo-hd-javier.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/changelog.d/20240227_142553_alexander.esgen_pipelining_criterion.md
  ouroboros-consensus-diffusion/changelog.d/20240328_165134_alexander.esgen_milestone_11_gdd_governor_squashed.md
  ouroboros-consensus-diffusion/changelog.d/20240425_110304_alexander.esgen_customize_prefer_candidate.md
  ouroboros-consensus-diffusion/changelog.d/20240429_143457_alexander.esgen_gsm_remote.md
  ouroboros-consensus-diffusion/changelog.d/20240508_072753_coot_ouroboros_network_0_16.md
  ouroboros-consensus-diffusion/changelog.d/chaindb-args-javier.md
  ouroboros-consensus-diffusion/changelog.d/utxo-hd-javier.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-protocol/CHANGELOG.md
  ouroboros-consensus-protocol/changelog.d/20240409_142855_alexander.esgen_duncan_tiebreaker.md
  ouroboros-consensus-protocol/changelog.d/20240417_122550_alexander.esgen_customize_prefer_candidate.md
  ouroboros-consensus-protocol/changelog.d/20240503_194253_alexander.esgen_praos_chain_order_truly_transitive.md
  ouroboros-consensus-protocol/changelog.d/delete-praos-translate.md
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/changelog.d/20240227_142208_alexander.esgen_pipelining_criterion.md
  ouroboros-consensus/changelog.d/20240227_142827_alexander.esgen_pipelining_criterion.md
  ouroboros-consensus/changelog.d/20240227_142942_alexander.esgen_pipelining_criterion.md
  ouroboros-consensus/changelog.d/20240227_143020_alexander.esgen_pipelining_criterion.md
  ouroboros-consensus/changelog.d/20240328_165134_alexander.esgen_milestone_11_gdd_governor_squashed.md
  ouroboros-consensus/changelog.d/20240417_122327_alexander.esgen_customize_prefer_candidate.md
  ouroboros-consensus/changelog.d/20240426_144237_alexander.esgen_chainsync_client_simplify_nextStep.md
  ouroboros-consensus/changelog.d/chaindb-args-javier.md
  ouroboros-consensus/changelog.d/orphans-javier.md
  ouroboros-consensus/changelog.d/proto-translate-javier.md
  ouroboros-consensus/changelog.d/utxo-hd-javier.md
  ouroboros-consensus/ouroboros-consensus.cabal
  sop-extras/CHANGELOG.md
  sop-extras/changelog.d/utxo-hd-javier.md
  sop-extras/sop-extras.cabal
  strict-sop-core/CHANGELOG.md
  strict-sop-core/changelog.d/utxo-hd-javier.md
  strict-sop-core/strict-sop-core.cabal
Labels: release

#1095 Ensure that transaction tokens are unique in the mempool benchmarks
  .gitignore
  ouroboros-consensus/bench/mempool-bench/Bench/Consensus/Mempool/TestBlock.hs
  ouroboros-consensus/bench/mempool-bench/Main.hs
Labels: no changelog

#1103 Re-remove ShowProxy SlotNo
  cabal.project
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/Orphans.hs
Labels: no changelog

#1082 UTXO-HD md docs
  docs/website/contents/for-developers/utxo-hd/for-developers.md
  docs/website/contents/for-developers/utxo-hd/for-public.md
  docs/website/contents/for-developers/utxo-hd/utxo-hd.md
  docs/website/sidebars.js
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/FollowerPromptness.hs
Labels: documentation, UTxO-HD

#1111 Allow to disable *all* Genesis components individually
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node/Genesis.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
  ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Network.hs
Labels: Genesis

#982 Add an initial formal specification
  docs/formal-spec/.gitignore
  docs/formal-spec/IOHKCoverPage.sty
  docs/formal-spec/Makefile
  docs/formal-spec/chain.tex
  docs/formal-spec/common-interface.tex
  docs/formal-spec/consensus-spec.bbl
  docs/formal-spec/consensus-spec.tex
  docs/formal-spec/crypto-details.tex
  docs/formal-spec/frontmatter.tex
  docs/formal-spec/habbrv.bst
  docs/formal-spec/iohk-share-logo.jpg
  docs/formal-spec/iohk.sty
  docs/formal-spec/leader-value.tex
  docs/formal-spec/properties.tex
  docs/formal-spec/rules.dot
  docs/formal-spec/rules.pdf
  docs/formal-spec/sts-overview.tex
  docs/website/contents/about-ouroboros/References.md
  nix/pdfs.nix
Labels: documentation, enhancement, formal-spec

#1116 Use simple diffs except in `DiffSeq`
  cabal.project
  flake.lock
  ouroboros-consensus-cardano/app/DBAnalyser/Parsers.hs
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/CanHardFork.hs
  ouroboros-consensus-cardano/test/cardano-test/Test/Consensus/Cardano/Translation.hs
  ouroboros-consensus/bench/backingstore-bench/Main.hs
  ouroboros-consensus/bench/mempool-bench/Bench/Consensus/Mempool/TestBlock.hs
  ouroboros-consensus/bench/mempool-bench/Main.hs
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/State/Types.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Abstract.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/Diff.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/MapKind.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Tables/Utils.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Impl/Common.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Args.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/BackingStore/Impl/InMemory.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/BackingStore/Impl/LMDB.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/DbChangelog.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Forker.hs
  ouroboros-consensus/test/consensus-test/Main.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Ledger/Tables/Diff.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Ledger/Tables/DiffSeq.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/StateMachine.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/V1/BackingStore.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/V1/DbChangelog/Unit.hs
Labels: UTxO-HD
