Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2024-10, with the labels that each got.

#1270 Make all STSs in the Agda spec executable
  docs/agda-spec/src/Axiom/Set.agda
  docs/agda-spec/src/Axiom/Set/Map.agda
  docs/agda-spec/src/Interface/ComputationalRelation.agda
  docs/agda-spec/src/Interface/HasAdd/Instance.agda
  docs/agda-spec/src/Interface/HasOrder.agda
  docs/agda-spec/src/Interface/HasOrder/Instance.agda
  docs/agda-spec/src/Interface/IsSet.agda
  docs/agda-spec/src/InterfaceLibrary/Ledger.lagda
  docs/agda-spec/src/Ledger/BaseTypes.lagda
  docs/agda-spec/src/Ledger/Crypto.lagda
  docs/agda-spec/src/Ledger/PParams.lagda
  docs/agda-spec/src/Ledger/Script.lagda
  docs/agda-spec/src/Ledger/Set/Theory.agda
  docs/agda-spec/src/Ledger/Types/Epoch.agda
  docs/agda-spec/src/Makefile
  docs/agda-spec/src/Spec/BlockDefinitions.lagda
  docs/agda-spec/src/Spec/ChainHead/Properties.agda
  docs/agda-spec/src/Spec/OperationalCertificate.lagda
  docs/agda-spec/src/Spec/OperationalCertificate/Properties.agda
  docs/agda-spec/src/Spec/PDF.lagda
  docs/agda-spec/src/Spec/Protocol.lagda
  docs/agda-spec/src/Spec/Protocol/Properties.agda
  docs/agda-spec/src/Spec/TickForecast/Properties.agda
  docs/agda-spec/src/Spec/TickNonce/Properties.agda
  docs/agda-spec/src/Spec/UpdateNonce/Properties.agda
  docs/agda-spec/src/latex/iohk.sty
Labels: enhancement, formal-spec, conformance

#1283 Release Consensus packages for Node 10.0
  README.md
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/changelog.d/20240711_064942_nick.frisby_consolidate_txlimits.md
  ouroboros-consensus-cardano/changelog.d/20240906_081159_nick.frisby_db_analyser_add_blocksize.md
  ouroboros-consensus-cardano/changelog.d/20240917_143437_damian.nadales.md
  ouroboros-consensus-cardano/changelog.d/20241014_135603_crocodile-dentist_integrate_latest_ledger.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/changelog.d/20240711_064938_nick.frisby_consolidate_txlimits.md
  ouroboros-consensus-diffusion/changelog.d/20240722_170436_alexander.esgen_historical_rollbacks.md
  ouroboros-consensus-diffusion/changelog.d/20240912_105915_alexander.esgen_gdd_disconnect_trace.md
  ouroboros-consensus-diffusion/changelog.d/20241014_135044_crocodile-dentist_integrate_latest_ledger.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-protocol/CHANGELOG.md
  ouroboros-consensus-protocol/changelog.d/20241014_141111_crocodile-dentist_integrate_latest_ledger.md
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/changelog.d/20240711_064934_nick.frisby_consolidate_txlimits.md
  ouroboros-consensus/changelog.d/20240722_170344_alexander.esgen_historical_rollbacks.md
  ouroboros-consensus/changelog.d/20240724_170351_alexander.esgen_loe_chaindb_qsm.md
  ouroboros-consensus/changelog.d/20240827_160651_alexander.esgen_test_empty_mempool_nonblocking.md
  ouroboros-consensus/changelog.d/20240829_095937_alexander.esgen_gdd_splitAtSlot.md
  ouroboros-consensus/changelog.d/20240903_154122_alexander.esgen_replay_snapshot_tracing_tweak.md
  ouroboros-consensus/changelog.d/20240912_105038_alexander.esgen_gdd_disconnect_trace.md
  ouroboros-consensus/changelog.d/20241008_190347_alexander.esgen_clock_skew_2_secs.md
  ouroboros-consensus/changelog.d/20241011_091242_karl.fb.knutsson_sync_tracing.md
  ouroboros-consensus/changelog.d/20241014_134104_crocodile-dentist_integrate_latest_ledger.md
  ouroboros-consensus/changelog.d/js-cache-modifymvar.md
  ouroboros-consensus/changelog.d/js-earlyexit.md
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: release

#1293 Nixify hlint
  .github/workflows/hlint.yml
  nix/ci.nix
  nix/formatting-linting.nix
  nix/shell.nix
  nix/tools.nix
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/DiffusionPipelining.hs
Labels: continuous integration, no changelog

#1298 Require `cardano-ledger-conway >=1.17.2`
  cabal.project
  flake.lock
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
Labels: no changelog
