Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2024-01, with the labels that each got.

#860 Fix broken links, update copyright-related info
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  NOTICE
  SECURITY.md
  asserts.cabal
  docs/tech-reports/report/unsoundswitch/NOTICE
  docs/tech-reports/report/unsoundswitch/unsoundswitch.cabal
  docs/website/contents/about-ouroboros/index.md
  docs/website/contents/for-developers/Glossary.md
  ouroboros-consensus-cardano/NOTICE
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/byron/Ouroboros/Consensus/Byron/Ledger/Orphans.hs
  ouroboros-consensus-diffusion/NOTICE
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-protocol/NOTICE
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/NOTICE
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/InFutureCheck.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/Paths.hs
  sop-extras/NOTICE
  sop-extras/sop-extras.cabal
  strict-sop-core/NOTICE
  strict-sop-core/strict-sop-core.cabal
Labels: no changelog

#859 Bump flake inputs and tools
  docs/website/contents/for-developers/ReleaseProcess.md
  flake.lock
  nix/shell.nix
  nix/tools.nix
Labels: continuous integration

#861 Bump `quickcheck-lockstep` to `>= 0.3`
  cabal.project
  flake.lock
  flake.nix
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/BackingStore.hs
Labels: UTxO-HD

#865 simplify the code handling ValidationTagMismatch and Alonzo-onwards transactions' isValid flags
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Eras.hs
Labels: no changelog

#869 Improve plan diff script and make it a GHA job
  .github/workflows/checks.yml
  docs/website/contents/for-developers/ReleaseProcess.md
  scripts/release/cabal-plan-diff.sh
Labels: continuous integration

#504 Add profiled Nix shells
  docs/website/contents/for-developers/ProfilingTipsAndTricks.md
  flake.nix
  nix/ci.nix
  nix/haskell.nix
Labels: continuous integration

#883 Write down expectations about tests in PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no changelog

#885 Update QSM, remove Sing and Dict
  .hlint.yaml
  cabal.project
  flake.lock
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/test/byron-test/Test/Consensus/Byron/Serialisation.hs
  ouroboros-consensus-cardano/test/cardano-test/Test/Consensus/Cardano/Serialisation.hs
  ouroboros-consensus-cardano/test/shelley-test/Test/Consensus/Shelley/Serialisation.hs
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-diffusion/test/mock-test/Test/ThreadNet/BFT.hs
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Lifting.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Protocol/LedgerView.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Serialisation/SerialiseDisk.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/Singletons.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/Serialisation/Roundtrip.hs
  scripts/release/cabal-plan-diff.sh
  sop-extras/src/Data/SOP/Counting.hs
  sop-extras/src/Data/SOP/Index.hs
Labels: no changelog

#889 QueryVersioning.md: elaborate on the query versioning scheme
  docs/website/contents/for-developers/QueryVersioning.md
Labels: documentation

#879 Initialize a "preflight guide"
  CONTRIBUTING.md
  docs/website/contents/for-developers/PreflightGuide.md
  docs/website/sidebars.js
Labels: documentation, no changelog

#900 Bump to GHC 9.6.4, update tools
  .github/workflows/ci.yml
  CONTRIBUTING.md
  flake.lock
  nix/haskell.nix
  nix/shell.nix
  nix/tools.nix
Labels: continuous integration

#878 Introduce the Limit on Eagerness
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBSynthesizer/Run.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/Uniform.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Trace.hs
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Fragment/Diff.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Genesis/Governor.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/API.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Args.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Paths.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/AnchoredFragment.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/ChainDB.hs
Labels: Genesis

#922 Make Conway query constructors ill-typed in pre-Conway eras
  ouroboros-consensus-cardano/changelog.d/20240124_143703_nick.frisby_conway_only_queries.md
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Eras.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Query.hs
Labels: Conway

#814 Make to build with ghc-9.8
  .github/workflows/ci.yml
  .github/workflows/documentation.yml
  cabal.project
  flake.lock
  ouroboros-consensus-cardano/changelog.d/20240129_115458_javier.sagredo_ghc_9_8.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Mempool.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/Praos.hs
  ouroboros-consensus-cardano/src/unstable-cardano-testlib/Test/Consensus/Cardano/Examples.hs
  ouroboros-consensus-diffusion/changelog.d/20240129_115203_javier.sagredo_ghc_9_8.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Network/NodeToClient.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node/ExitPolicy.hs
  ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Util/NodeJoinPlan.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/BlockTree.hs
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/changelog.d/20240129_115103_javier.sagredo_ghc_9_8.md
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Forging.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Basics.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/LocalStateQuery/Server.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Protocol/PBFT.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/Range.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/LocalStateQuery/Server.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/Adversarial.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ImmutableDB/Primary.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/OnDisk.hs
  sop-extras/sop-extras.cabal
  strict-sop-core/strict-sop-core.cabal
Labels: no changelog

#928 Release for Node 8.8
  README.md
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/changelog.d/20231212_174729_fraser.murray_warning_cpp_conditional.md
  ouroboros-consensus-cardano/changelog.d/20231218_150820_joris_bump_strict_checked_vars_0_2_0_0.md
  ouroboros-consensus-cardano/changelog.d/20240104_195829_alexander.esgen_homogenous_cardano_n2c_versions.md
  ouroboros-consensus-cardano/changelog.d/20240124_110740_nick.frisby_remove_ntn_hfcdisableera.md
  ouroboros-consensus-cardano/changelog.d/20240124_143703_nick.frisby_conway_only_queries.md
  ouroboros-consensus-cardano/changelog.d/20240126_202311_unsafeFixIO_880.md
  ouroboros-consensus-cardano/changelog.d/20240129_115458_javier.sagredo_ghc_9_8.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/changelog.d/20231129_105548_nick.frisby_ChainSync_future.md
  ouroboros-consensus-diffusion/changelog.d/20231206_171853_nick.frisby_ChainSync_refactor.md
  ouroboros-consensus-diffusion/changelog.d/20231218_150810_joris_bump_strict_checked_vars_0_2_0_0.md
  ouroboros-consensus-diffusion/changelog.d/20240124_110627_nick.frisby_remove_ntn_hfcdisableera.md
  ouroboros-consensus-diffusion/changelog.d/20240126_202852_unsafeFixIO_880.md
  ouroboros-consensus-diffusion/changelog.d/20240129_115203_javier.sagredo_ghc_9_8.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-protocol/CHANGELOG.md
  ouroboros-consensus-protocol/changelog.d/20231218_150814_joris_bump_strict_checked_vars_0_2_0_0.md
  ouroboros-consensus-protocol/changelog.d/20240129_105412_javier.sagredo_880.md
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/changelog.d/20231129_105543_nick.frisby_ChainSync_future.md
  ouroboros-consensus/changelog.d/20231206_171848_nick.frisby_ChainSync_refactor.md
  ouroboros-consensus/changelog.d/20231218_150141_joris_bump_strict_checked_vars_0_2_0_0.md
  ouroboros-consensus/changelog.d/20240124_110230_nick.frisby_remove_ntn_hfcdisableera.md
  ouroboros-consensus/changelog.d/20240126_122429_alexander.esgen_mempool_remove_trace_reason.md
  ouroboros-consensus/changelog.d/20240126_202443_unsafeFixIO_880.md
  ouroboros-consensus/changelog.d/20240129_115103_javier.sagredo_ghc_9_8.md
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: no changelog

#929 Only limit initial chain selection length when LoE is active
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
Labels: Genesis

#931 Add GHC 9.8.1 to Nix CI
  flake.nix
  nix/ci.nix
  nix/haskell.nix
  nix/shell.nix
Labels: continuous integration

#933 merge LoE config types
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/API.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Args.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/ChainDB.hs
Labels: Genesis
