Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2024-04, with the labels that each got.

#959 cabal-fmt -> cabal-gild
  CONTRIBUTING.md
  nix/formatting.nix
  nix/shell.nix
  nix/tools.nix
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/ouroboros-consensus.cabal
  scripts/ci/run-cabal-gild.sh
  sop-extras/sop-extras.cabal
  strict-sop-core/strict-sop-core.cabal
Labels: no changelog

#1042 PeerSharingAPI fix - backport
  .github/workflows/checks.yml
  cabal.project
  flake.lock
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
  ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Network.hs
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: no changelog

#1050 Release ouroboros-consensus packages for Node 8.10.1.
  README.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/changelog.d/20240404_233318_coot_peerSharingAPI_fix.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
Labels: no changelog

#1052 Add `latex-svg-image` for haddocks
  .gitignore
  cabal.project
  flake.lock
  ouroboros-consensus/docs/haddocks/bogus.svg
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB.hs
  ouroboros-consensus/test/doctest.hs
  scripts/docs/haddocks.sh
Labels: documentation, no changelog

#1055 Add `release` label for CI
  .github/workflows/checks.yml
  scripts/ci/check-changelogs.sh
Labels: continuous integration

#1060 Fix haddocks on `main`
  .github/workflows/ci.yml
  scripts/docs/haddocks.sh
Labels: documentation, continuous integration

#1034 ReleaseProcess: retrofit release/backport branch rules
  docs/website/contents/for-developers/ReleaseProcess.md
Labels: documentation

#1073 Factor out class `ShelleyBasedBlock` and type family `ShelleyBlockLedgerEra`
  ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Node.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Block.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Block/Cardano.hs
Labels: no changelog

#1079 LoP: more robust pausing while waiting for horizon advancement
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client.hs
Labels: Genesis

#1038 Enter ChainSync jumping - Governor-less approach
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Network/NodeToNode.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Network.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup/GenChains.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/Uniform.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/ChainSync.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Trace.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule/Peers.hs
  ouroboros-consensus/bench/ChainSync-client-bench/Main.hs
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/Jumping.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/State.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/ChainSync/Client.hs
Labels: Genesis

#1061 Fix prop_densityDisconnectMonotonic
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/DensityDisconnect.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Trace.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule/Peers.hs
Labels: Genesis, no changelog
