Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2024-09, with the labels that each got.

#1233 Add ^>= 1.14 bound to cardano-ledger-core in ouroboros-consensus
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: no changelog

#1235 Require `cardano-ledger-shelley >=1.13.1`
  cabal.project
  flake.lock
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
Labels: no changelog

#1175 Consolidate TxLimits
  ouroboros-consensus-cardano/changelog.d/20240711_064942_nick.frisby_consolidate_txlimits.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/byron/Ouroboros/Consensus/Byron/Ledger/Forge.hs
  ouroboros-consensus-cardano/src/byron/Ouroboros/Consensus/Byron/Ledger/Mempool.hs
  ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/CanHardFork.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Eras.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Forge.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Mempool.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/Common.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/Praos.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Node/TPraos.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/ShelleyHFC.hs
  ouroboros-consensus-cardano/src/unstable-byronspec/Ouroboros/Consensus/ByronSpec/Ledger/Mempool.hs
  ouroboros-consensus-cardano/src/unstable-cardano-testlib/Test/ThreadNet/Infra/ShelleyBasedHardFork.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis.hs
  ouroboros-consensus-cardano/test/cardano-test/Test/Consensus/Cardano/MiniProtocol/LocalTxSubmission/Server.hs
  ouroboros-consensus-cardano/test/shelley-test/Test/Consensus/Shelley/Coherence.hs
  ouroboros-consensus-diffusion/changelog.d/20240711_064938_nick.frisby_consolidate_txlimits.md
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
  ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Network.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator/A.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator/B.hs
  ouroboros-consensus/bench/mempool-bench/Bench/Consensus/Mempool/TestBlock.hs
  ouroboros-consensus/bench/mempool-bench/Main.hs
  ouroboros-consensus/changelog.d/20240711_064934_nick.frisby_consolidate_txlimits.md
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Block/Forging.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Abstract/CanHardFork.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Mempool.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Dual.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/SupportsMempool.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/API.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Capacity.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Impl/Common.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Init.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/TxSeq.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Update.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/LocalTxMonitor/Server.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/TypeFamilyWrappers.hs
  ouroboros-consensus/src/unstable-mempool-test-utils/Test/Consensus/Mempool/Mocked.hs
  ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Ledger/Block.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool/Fairness.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool/Fairness/TestBlock.hs
Labels: component-mempool

#1186 ChainSync client: allow to prevent historical `MsgRollBackward`/`MsgAwaitReply`
  ouroboros-consensus-diffusion/changelog.d/20240722_170436_alexander.esgen_historical_rollbacks.md
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Network/NodeToNode.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node/Genesis.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
  ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Network.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/ChainSync.hs
  ouroboros-consensus/bench/ChainSync-client-bench/Main.hs
  ouroboros-consensus/changelog.d/20240722_170344_alexander.esgen_historical_rollbacks.md
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HeaderStateHistory.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HeaderValidation.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/HistoricityCheck.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/InFutureCheck.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/API.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Query.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/ChainSync/Client.hs
Labels: Genesis

#1228 Bump `fs-sim` and `fs-api` dependencies to `^>=0.3`
  cabal.project
  flake.lock
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Network.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Setup.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/NodeLifecycle.hs
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/ChainDB.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/StateMachine.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ImmutableDB/StateMachine.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/OnDisk.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/VolatileDB/StateMachine.hs
Labels: dependencies, no changelog

#1237 Run mempool benchmarks in a separate GHA job
  .github/workflows/ci.yml
Labels: no changelog

#1215 Add overview of the tasks of a caught-up node
  docs/website/contents/for-developers/NodeTasks.md
  docs/website/sidebars.js
Labels: documentation, no changelog

#1243 db-analyser: fully document output of `--benchmark-ledger-ops`
  ouroboros-consensus-cardano/README.md
Labels: documentation, no changelog

#1232 Close forkers when exiting the forging loop early
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
Labels: UTxO-HD

#1222 Snapshot-converter
  ouroboros-consensus-cardano/app/snapshot-converter.hs
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Ledger.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/BackingStore/Impl/LMDB.hs
Labels: UTxO-HD

#1244 GDD: add separate trace event for disconnections
  ouroboros-consensus-diffusion/changelog.d/20240912_105915_alexander.esgen_gdd_disconnect_trace.md
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Trace.hs
  ouroboros-consensus/changelog.d/20240912_105038_alexander.esgen_gdd_disconnect_trace.md
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Genesis/Governor.hs
Labels: Genesis

#1234 Rework UTxO-HD args
  ouroboros-consensus-cardano/app/DBAnalyser/Parsers.hs
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Run.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Types.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBSynthesizer/Run.hs
  ouroboros-consensus-cardano/test/tools-test/Main.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Network.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Args.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Impl/Args.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/Impl/Snapshots.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Args.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/BackingStore.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/BackingStore/API.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/BackingStore/Impl/InMemory.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/BackingStore/Impl/LMDB.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Common.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Init.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V1/Snapshots.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/Common.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/Init.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/ChainDB.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/LocalStateQuery/Server.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/StateMachine.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/V1/BackingStore.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/LedgerDB/V1/BackingStore/Lockstep.hs
Labels: UTxO-HD

#1249 Update docusaurus
  docs/website/package.json
  docs/website/yarn.lock
Labels: documentation

#1253 Enforce LF line endings
  nix/formatting.nix
  nix/shell.nix
  scripts/ci/run-dos2unix.sh
Labels: no changelog

#1254 Update SECURITY.md
  SECURITY.md
Labels: no changelog

#1230 Mempool test: generate txs larger than the entire mempool
  ouroboros-consensus/changelog.d/20240827_160651_alexander.esgen_test_empty_mempool_nonblocking.md
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/SupportsMempool.hs
  ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Ledger/Block.hs
  ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Ledger/State.hs
  ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Node/BFT.hs
  ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Node/PBFT.hs
  ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Node/Praos.hs
  ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Node/PraosRule.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool.hs
Labels: component-mempool, better-tests

#1264 Trace the right `CoreNodeId` in protocol tracing
  ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Network.hs
Labels: no changelog
