Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2024-06, with the labels that each got.

#1084 GHC minor bump in CI
  .github/workflows/ci.yml
  flake.lock
  flake.nix
  nix/haskell.nix
  nix/shell.nix
  nix/tools.nix
  scripts/docs/haddocks.sh
Labels: continuous integration

#1133 Fix bug when calling `OCERT` from `PRTCL`
  docs/formal-spec/chain.tex
Labels: bug, documentation, formal-spec

#1125 Small tweaks to the LoE
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Paths.hs
Labels: Genesis

#1132 DBSynthesizer: pass a tx-generating function to runForge
  ouroboros-consensus-cardano/app/db-synthesizer.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Node/Protocol/Cardano.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBSynthesizer/Forging.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBSynthesizer/Run.hs
  ouroboros-consensus-cardano/test/tools-test/Main.hs
Labels: no changelog

#1136 Fix minor bug in `CHAINHEAD` of formal spec
  docs/formal-spec/chain.tex
Labels: bug, documentation, formal-spec

#1137 Fix minor bug in `prtlSeqChecks` of formal spec
  docs/formal-spec/chain.tex
Labels: bug, documentation, formal-spec

#1138 Fix wrong use of `hBBodyHash` in `CHAINHEAD` in the formal spec
  docs/formal-spec/chain.tex
Labels: bug, documentation, formal-spec

#1131 Fix GHC versions in CI workflow
  .github/workflows/ci.yml
  .github/workflows/hlint.yml
  cabal.project
  flake.lock
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/LoE.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/Jumping.hs
Labels: no changelog

#1144 CI cosmetics: move os and cabal out of matrix definition
  .github/workflows/ci.yml
Labels: continuous integration

#1151 Release Consensus packages for Node 8.12
  README.md
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/changelog.d/20240610_154105_alexander.esgen_db_immutaliser.md
  ouroboros-consensus-cardano/changelog.d/20240613_134008_alexander.esgen_immdb_slots.md
  ouroboros-consensus-cardano/changelog.d/20240617_202003_alexander.esgen_cardano_node_8_12.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/changelog.d/20240430_180423_niols_milestone_12_chain_sync_jumping.md
  ouroboros-consensus-diffusion/changelog.d/20240618_100729_nick.frisby_cardano_node_8_12.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-protocol/CHANGELOG.md
  ouroboros-consensus-protocol/changelog.d/20240618_100858_nick.frisby_cardano_node_8_12.md
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/changelog.d/20240430_180423_niols_milestone_12_chain_sync_jumping.md
  ouroboros-consensus/changelog.d/20240613_133641_alexander.esgen_immdb_slots.md
  ouroboros-consensus/changelog.d/20240613_133842_alexander.esgen_immdb_slots.md
  ouroboros-consensus/changelog.d/20240618_100605_nick.frisby_cardano_node_8_12.md
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: release

#1152 db-analyser: print hashes for `--show-slot-block-no`
  ouroboros-consensus-cardano/README.md
  ouroboros-consensus-cardano/app/DBAnalyser/Parsers.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis.hs
Labels: no changelog

#1154 Update haskell.nix, remove workarounds
  cabal.project
  flake.lock
Labels: continuous integration

#1155 db-analyser: support full block application in `--store-ledger`
  ouroboros-consensus-cardano/README.md
  ouroboros-consensus-cardano/app/DBAnalyser/Parsers.hs
  ouroboros-consensus-cardano/app/db-analyser.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Types.hs
Labels: no changelog

#1161 Use tasty-quickcheck-0.11
  cabal.project
  flake.lock
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: no changelog

#1163 Document `GenesisWindow`
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Block/Abstract.hs
Labels: Genesis, no changelog

#1166 Release Consensus packages for Node 8.12.1
  README.md
  cabal.project
  flake.lock
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/byron/Ouroboros/Consensus/Byron/Ledger/Mempool.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Eras.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Mempool.hs
  ouroboros-consensus-cardano/src/unstable-byronspec/Ouroboros/Consensus/ByronSpec/Ledger/Mempool.hs
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator/A.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator/B.hs
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/bench/mempool-bench/Bench/Consensus/Mempool/TestBlock.hs
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Mempool.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Dual.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/SupportsMempool.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Impl/Common.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/TxSeq.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Update.hs
  ouroboros-consensus/src/unstable-mock-block/Ouroboros/Consensus/Mock/Ledger/Block.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool/Fairness/TestBlock.hs
Labels: no changelog

#1170 db-analyser: only print microsecond timestamps
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Run.hs
Labels: no changelog

#1169 db-analyser: document pitfall of `--repro-mempool-and-forge 2`
  ouroboros-consensus-cardano/README.md
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis.hs
Labels: no changelog
