Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2024-08, with the labels that each got.

#1199 Allow for different DB paths for immutable and volatile data
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Run.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBSynthesizer/Run.hs
  ouroboros-consensus-diffusion/changelog.d/js-flexible-databases.md
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node.hs
  ouroboros-consensus/changelog.d/js-flexible-databases.md
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Args.hs
Labels: no changelog

#1203 db-truncater: make `--truncate-after-slot` more lenient again
  ouroboros-consensus-cardano/app/DBTruncater/Parsers.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBTruncater/Run.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBTruncater/Types.hs
Labels: no changelog

#1206 db-synthesizer: explain what "does not look like a ChainDB" means
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBSynthesizer/Run.hs
Labels: no changelog

#1213 Allow `containers-0.7`
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: no changelog

#1208 RAWLock on the LedgerDB (V2)
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Dual.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/Common.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2/Init.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/MonadSTM/RAWLock.hs
Labels: UTxO-HD

#1188 Nix/Hydra/GHA: add GHC 9.10, drop GHC 9.8
  .github/workflows/ci.yml
  cabal.project
  flake.lock
  flake.nix
  nix/ci.nix
  nix/haskell.nix
Labels: continuous integration, no changelog

#1201 reduce the frequency of client and server diverging before they reach startTick
  ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/ChainSync/Client.hs
Labels: no changelog

#1219 db-analyser: support reapplication in `--benchmark-ledger-ops`
  ouroboros-consensus-cardano/README.md
  ouroboros-consensus-cardano/app/DBAnalyser/Parsers.hs
  ouroboros-consensus-cardano/app/db-analyser.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis/BenchmarkLedgerOps/FileWriting.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis/BenchmarkLedgerOps/Metadata.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Types.hs
Labels: no changelog

#1221 db-synthesizer: relax check whether a dir "looks like a ChainDB"
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBSynthesizer/Run.hs
Labels: no changelog

#1225 Mempool: reject txs that don't fit in an empty mempool
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Update.hs
Labels: no changelog

#1227 mempool-bench: move more pre-calculation into withResource
  ouroboros-consensus/bench/mempool-bench/Main.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Capacity.hs
Labels: component-mempool, no changelog

#1119 Add LoE to the ChainDB QSM test
  ouroboros-consensus/changelog.d/20240724_170351_alexander.esgen_loe_chaindb_qsm.md
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Genesis/Governor.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/API.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Background.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/Orphans/Arbitrary.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/Orphans/ToExpr.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/Model.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/Model/Test.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/StateMachine.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/StateMachine/Utils/RunOnRepl.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/Unit.hs
Labels: Genesis
