Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2024-02, with the labels that each got.

#904 Implement `Electric` and enclose relevant code
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Background.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util.hs
Labels: no changelog

#956 Stream test details to stdout in GHA
  .github/workflows/ci.yml
Labels: continuous integration

#957 Ensure UTF-8 support of all terminal handles
  ouroboros-consensus-cardano/app/db-analyser.hs
  ouroboros-consensus-cardano/app/db-synthesizer.hs
  ouroboros-consensus-cardano/app/db-truncater.hs
  ouroboros-consensus-cardano/app/immdb-server.hs
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/test/cardano-test/Main.hs
  ouroboros-consensus/bench/ChainSync-client-bench/Main.hs
  ouroboros-consensus/bench/mempool-bench/Main.hs
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/TestEnv.hs
  scripts/release/create-release.hs
Labels: no changelog

#960 Better pretty-printing for `Peers PeerSchedule`
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule/Peers.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/Condense.hs
Labels: Genesis

#946 Make db-analyser the same ghc-options as in the node
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
Labels: no changelog

#969 Release ouroboros-consensus packages
  README.md
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/changelog.d/20240208_130918_renate.eilers_expose_diskNumShapshots_as_flag.md
  ouroboros-consensus-cardano/changelog.d/20240223_135546_armandoifsantos_integrate.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/changelog.d/20240208_125609_renate.eilers_expose_diskNumShapshots_as_flag.md
  ouroboros-consensus-diffusion/changelog.d/20240220_122811_nick.frisby_bootstrap_gsm.md
  ouroboros-consensus-diffusion/changelog.d/20240223_135212_armandoifsantos_integrate.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/changelog.d/20240208_130104_renate.eilers_expose_diskNumShapshots_as_flag.md
  ouroboros-consensus/changelog.d/20240212_141854_alexander.esgen_the_answer_is_traverse.md
  ouroboros-consensus/changelog.d/20240220_122808_nick.frisby_bootstrap_gsm.md
  ouroboros-consensus/changelog.d/20240223_133210_armandoifsantos_integrate.md
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: no changelog

#927 Praos: use larger nonce stabilization window starting in Conway
  docs/website/contents/for-developers/Glossary.md
  ouroboros-consensus-cardano/changelog.d/20240206_174354_alexander.esgen_change_epoch_structure.md
  ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Node.hs
  ouroboros-consensus-protocol/changelog.d/20240206_174037_alexander.esgen_change_epoch_structure.md
  ouroboros-consensus-protocol/changelog.d/20240206_174209_alexander.esgen_change_epoch_structure.md
  ouroboros-consensus-protocol/src/ouroboros-consensus-protocol/Ouroboros/Consensus/Protocol/Praos.hs
  ouroboros-consensus-protocol/src/ouroboros-consensus-protocol/Ouroboros/Consensus/Protocol/Praos/Translate.hs
  ouroboros-consensus-protocol/src/ouroboros-consensus-protocol/Ouroboros/Consensus/Protocol/Translate.hs
Labels: do-not-merge
