Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2025-05, with the labels that each got.

#1498 consensus: more carefully hide `HeaderWithTime` from traces
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Trace.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Genesis/Governor.hs
Labels: no changelog

#1488 add Show instance for HardForkLedgerConfig
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/byron/Ouroboros/Consensus/Byron/ByronHFC.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Block.hs
  ouroboros-consensus-cardano/src/shelley/Ouroboros/Consensus/Shelley/Ledger/Ledger.hs
  ouroboros-consensus-cardano/test/cardano-test/Main.hs
  ouroboros-consensus-cardano/test/cardano-test/Test/Consensus/Cardano/Show.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/HardFork/Combinator/A.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/AcrossEras.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Basics.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/PartialConfig.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Dual.hs
Labels: no changelog

#1504 Remove TODO on only running the GDD with (big) ledger peers
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
Labels: Genesis, no changelog

#1510 Release Consensus for node 10.5
  README.md
  cabal.project
  flake.lock
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/changelog.d/20250430_141707_alexander.esgen_drop_ghc810.md
  ouroboros-consensus-cardano/changelog.d/20250513_142405_crocodile-dentist_integrate_o_network.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/changelog.d/20241218_095040_nick.frisby_annotate_headers_with_time.md
  ouroboros-consensus-diffusion/changelog.d/20250430_141654_alexander.esgen_drop_ghc810.md
  ouroboros-consensus-diffusion/changelog.d/20250513_152607_crocodile-dentist_integrate_o_network.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/changelog.d/20241218_095010_nick.frisby_annotate_headers_with_time.md
  ouroboros-consensus/changelog.d/20250429_155724_alexander.esgen_follower_forward_bug.md
  ouroboros-consensus/changelog.d/20250430_141645_alexander.esgen_drop_ghc810.md
  ouroboros-consensus/changelog.d/20250505_133127_alexander.esgen_getledgerconfig_query_debug.md
  ouroboros-consensus/changelog.d/20250506_090817_nick.frisby_bugfix_csj_gsm.md
  ouroboros-consensus/changelog.d/20250513_152215_crocodile-dentist_integrate_o_network.md
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: release

#1505 GDD: trigger chain selection when caught-up
  ouroboros-consensus-diffusion/changelog.d/20250512_165249_alexander.esgen_genesis_caughtup_final_chainsel.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/LoE.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/LoE/CaughtUp.hs
  ouroboros-consensus/changelog.d/20250512_164809_alexander.esgen_genesis_caughtup_final_chainsel.md
  ouroboros-consensus/changelog.d/20250512_165110_alexander.esgen_genesis_caughtup_final_chainsel.md
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Genesis/Governor.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
Labels: Genesis

#1512 `db-analyser --store-ledger`: fix two bugs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/LedgerDB/V2.hs
Labels: no changelog

#1524 Bump GHC versions, bump haskell.nix, bump pinned tools
  .github/workflows/checks.yml
  .github/workflows/ci.yml
  flake.lock
  flake.nix
  nix/ci.nix
  nix/ghcide-workaround.diff
  nix/haskell.nix
  nix/shell.nix
  nix/tools.nix
  ouroboros-consensus-cardano/README.md
Labels: continuous integration
