Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2025-04, with the labels that each got.

#1439 Remove custom QuickCheck `elements`
  ouroboros-consensus-diffusion/src/unstable-diffusion-testlib/Test/ThreadNet/Util/NodeToNodeVersion.hs
  ouroboros-consensus-diffusion/src/unstable-mock-testlib/Test/ThreadNet/TxGen/Mock.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PointSchedule/Tests.hs
  ouroboros-consensus-protocol/test/protocol-test/Test/Consensus/Protocol/Praos/SelectView.hs
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/QuickCheck.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/HardFork/Forecast.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/HardFork/Infra.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/Mempool.hs
  ouroboros-consensus/test/infra-test/Test/Ouroboros/Consensus/ChainGenerator/Tests/Adversarial.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/StateMachine.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/VolatileDB/StateMachine.hs
Labels: no changelog

#1440 Release ouroboros-consensus-0.24 and ouroboros-consensus-cardano-0.23
  README.md
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/changelog.d/20241218_095046_nick.frisby_annotate_headers_with_time.md
  ouroboros-consensus-cardano/changelog.d/js-index.md
  ouroboros-consensus-cardano/changelog.d/js-query-version.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/changelog.d/js-query-version.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/changelog.d/20241218_095010_nick.frisby_annotate_headers_with_time.md
  ouroboros-consensus/changelog.d/js-index.md
  ouroboros-consensus/changelog.d/js-query-version.md
  ouroboros-consensus/ouroboros-consensus.cabal
  scripts/ci/check-changelogs.sh
  sop-extras/CHANGELOG.md
  sop-extras/changelog.d/js-index.md
  sop-extras/sop-extras.cabal
Labels: release

#1449 Update index states
  cabal.project
  flake.lock
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis/BenchmarkLedgerOps/FileWriting.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Analysis/BenchmarkLedgerOps/SlotDataPoint.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Block/Byron.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Block/Cardano.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/Block/Shelley.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/CSV.hs
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBAnalyser/HasAnalysis.hs
Labels: no changelog

#1457 Add migration guide for UTxO-HD
  docs/website/contents/for-developers/utxo-hd/migrating.md
  docs/website/sidebars.js
Labels: UTxO-HD

#1468 Release Consensus for node 10.4
  README.md
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/changelog.d/utxo-hd.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/changelog.d/utxo-hd.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/changelog.d/20250409_105921_alexander.esgen_reduce_clock_skew.md
  ouroboros-consensus/changelog.d/utxo-hd.md
  ouroboros-consensus/ouroboros-consensus.cabal
  sop-extras/CHANGELOG.md
  sop-extras/changelog.d/utxo-hd.md
  sop-extras/sop-extras.cabal
Labels: release

#1476 Release consensus for 10.4
  README.md
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/changelog.d/20250418_171804_javier.sagredo_sharing_txout.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/CHANGELOG.md
  ouroboros-consensus-diffusion/changelog.d/20250418_171810_javier.sagredo_sharing_txout.md
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-protocol/CHANGELOG.md
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/changelog.d/20250418_171755_javier.sagredo_sharing_txout.md
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: release

#1288 consensus: annotate headers with their slot's RelativeTime
  ouroboros-consensus-diffusion/changelog.d/20241218_095040_nick.frisby_annotate_headers_with_time.md
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Network/NodeToNode.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/Node/Genesis.hs
  ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs
  ouroboros-consensus-diffusion/src/unstable-mock-testlib/Test/ThreadNet/Util/SimpleBlock.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/Genesis/Tests/DensityDisconnect.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/BlockFetch.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/NodeLifecycle.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Run.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Consensus/PeerSimulator/Trace.hs
  ouroboros-consensus-diffusion/test/consensus-test/Test/Util/TersePrinting.hs
  ouroboros-consensus/bench/ChainSync-client-bench/Main.hs
  ouroboros-consensus/changelog.d/20241218_095010_nick.frisby_annotate_headers_with_time.md
  ouroboros-consensus/ouroboros-consensus.cabal
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Block/Abstract.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Fragment/Diff.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Genesis/Governor.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HeaderValidation.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/BlockFetch/ClientInterface.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/Jumping.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/MiniProtocol/ChainSync/Client/State.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/API.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Background.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Follower.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Query.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Util/AnchoredFragment.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/Header.hs
  ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/TestBlock.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/BlockFetch/Client.hs
  ouroboros-consensus/test/consensus-test/Test/Consensus/MiniProtocol/ChainSync/Client.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/ChainDB/StateMachine.hs
  ouroboros-consensus/test/storage-test/Test/Ouroboros/Storage/TestBlock.hs
Labels: technical debt

#1483 Do not UNPACK the sum `TxOut`s in `CardanoTxOut`
  README.md
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/changelog.d/20250425_093611_javier.sagredo_unpack.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
Labels: release

#1484 Forward porting of #1483
  README.md
  ouroboros-consensus-cardano/CHANGELOG.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Ledger.hs
Labels: no changelog

#1482 db-immutaliser: more info on volatile candidates
  ouroboros-consensus-cardano/README.md
  ouroboros-consensus-cardano/app/db-immutaliser.hs
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-cardano/src/unstable-cardano-tools/Cardano/Tools/DBImmutaliser/Run.hs
  ouroboros-consensus-cardano/test/tools-test/Main.hs
Labels: no changelog
