Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2025-02, with the labels that each got.

#1384 Move a couple of mempool operations to work on ledgerstates instead
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Mempool.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Ledger/SupportsMempool.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Impl/Common.hs
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/Mempool/Update.hs
Labels: component-mempool, UTxO-HD

#1385 docs: draft Ticking.md
  docs/website/contents/for-developers/Ticking.md
  docs/website/sidebars.js
Labels: documentation, no changelog

#1395 CivicTime.md: fix trivial typos
  docs/website/contents/for-developers/CivicTime.md
Labels: no changelog

#1399 A more precise type for Nary.inject
  ouroboros-consensus-cardano/src/unstable-cardano-testlib/Test/Consensus/Cardano/Examples.hs
  ouroboros-consensus/changelog.d/20250219_054827_nick.frisby_simplify_inject.md
  ouroboros-consensus/src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Embed/Nary.hs
Labels: technical debt
