Repository IntersectMBO/ouroboros-consensus, pull requests merged in 2025-03, with the labels that each got.

#1419 EraTransitionGovernance.md: fixup hyperlink markup
  docs/website/contents/for-developers/EraTransitionGovernance.md
Labels: no changelog

#1420 Draft BlockBlockDiagram.md
  docs/website/contents/for-developers/BlockBlockDiagram.md
  docs/website/sidebars.js
Labels: documentation

#1315 Generate Haskell code from the Agda spec
  README.md
  docs/agda-spec/README.md
  docs/agda-spec/nix/sources.json
  docs/agda-spec/nix/sources.nix
  docs/agda-spec/src/Data/Rational/Ext.agda
  docs/agda-spec/src/Everything.agda
  docs/agda-spec/src/Foreign/Convertible.agda
  docs/agda-spec/src/Foreign/Convertible/Deriving.agda
  docs/agda-spec/src/Foreign/Convertible/DerivingTest.agda
  docs/agda-spec/src/Foreign/HaskellTypes.agda
  docs/agda-spec/src/Foreign/HaskellTypes/Deriving.agda
  docs/agda-spec/src/InterfaceLibrary/Ledger.lagda
  docs/agda-spec/src/Ledger/Crypto.lagda
  docs/agda-spec/src/Ledger/PParams.lagda
  docs/agda-spec/src/Ledger/Script.lagda
  docs/agda-spec/src/Ledger/Types/Epoch.agda
  docs/agda-spec/src/Makefile
  docs/agda-spec/src/Spec/BaseTypes.lagda
  docs/agda-spec/src/Spec/BlockDefinitions.lagda
  docs/agda-spec/src/Spec/ChainHead.lagda
  docs/agda-spec/src/Spec/ChainHead/Properties.agda
  docs/agda-spec/src/Spec/Foreign/ExternalFunctions.agda
  docs/agda-spec/src/Spec/Foreign/HSConsensus.agda
  docs/agda-spec/src/Spec/Foreign/HSConsensus/BaseTypes.agda
  docs/agda-spec/src/Spec/Foreign/HSConsensus/BlockDefinitions.agda
  docs/agda-spec/src/Spec/Foreign/HSConsensus/ChainHead.agda
  docs/agda-spec/src/Spec/Foreign/HSConsensus/Core.agda
  docs/agda-spec/src/Spec/Foreign/HSConsensus/ExternalStructures.agda
  docs/agda-spec/src/Spec/Foreign/HSConsensus/OperationalCertificate.agda
  docs/agda-spec/src/Spec/Foreign/HSConsensus/Protocol.agda
  docs/agda-spec/src/Spec/Foreign/HSConsensus/TickForecast.agda
  docs/agda-spec/src/Spec/Foreign/HSConsensus/TickNonce.agda
  docs/agda-spec/src/Spec/Foreign/HSConsensus/UpdateNonce.agda
  docs/agda-spec/src/Spec/Foreign/HSTypes.agda
  docs/agda-spec/src/Spec/Foreign/Util.agda
  docs/agda-spec/src/Spec/OperationalCertificate.lagda
  docs/agda-spec/src/Spec/OperationalCertificate/Properties.agda
  docs/agda-spec/src/Spec/Protocol.lagda
  docs/agda-spec/src/Spec/Protocol/Properties.agda
  docs/agda-spec/src/Spec/TickForecast.lagda
  docs/agda-spec/src/Spec/TickForecast/Properties.agda
  docs/agda-spec/src/Spec/TickNonce.lagda
  docs/agda-spec/src/Spec/TickNonce/Properties.agda
  docs/agda-spec/src/Spec/hs-src/LICENSE
  docs/agda-spec/src/Spec/hs-src/Lib.hs
  docs/agda-spec/src/Spec/hs-src/NOTICE
  docs/agda-spec/src/Spec/hs-src/cabal.project
  docs/agda-spec/src/Spec/hs-src/cardano-consensus-executable-spec.cabal
  docs/agda-spec/src/Spec/hs-src/test/ChainHeadSpec.hs
  docs/agda-spec/src/Spec/hs-src/test/OperationalCertificateSpec.hs
  docs/agda-spec/src/Spec/hs-src/test/ProtocolSpec.hs
  docs/agda-spec/src/Spec/hs-src/test/Spec.hs
  docs/agda-spec/src/Spec/hs-src/test/TickForecastSpec.hs
  docs/agda-spec/src/Spec/hs-src/test/TickNonceSpec.hs
  docs/agda-spec/src/Spec/hs-src/test/UpdateNonceSpec.hs
  docs/agda-spec/src/Tactic/Substitute.agda
  docs/agda-spec/src/formal-consensus.agda-lib
  nix/agda.nix
Labels: enhancement, formal-spec, conformance
